spring.application.name=ecommerce-backend
spring.datasource.url=jdbc:oracle:thin:@localhost:1525:orcl
spring.datasource.username=hr
spring.datasource.password=hr1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8088
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=yourSuperSecretKeyYourSuperSecretKey
jwt.expiration=86400000

stripe.secret.key=sk_test_your_secret_key_here

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.Oracle10gDialect




